brew tap aws/tap
brew install nvm
brew install terraform
brew install tmux
brew install docker
brew install docker-machine
brew install jq
brew install vifm
brew install postgis
brew install postgresql
brew install yarn
brew install z
brew install neovim
brew install python@3.8
brew install tree
brew install neovim
brew install fzf
brew install ripgrep
brew install the_silver_searcher
brew install awscli
brew install aws-sam-cli
brew install terraform
brew install tldr
brew installl httpie
brew install htop
brew install xsv
brew install thefuck
brew install zsh-autosuggestions
brew install zsh-syntax-highlighting
brew install zsh-completions
brew install autojump
brew install task
brew install figlet
brew install lazygit
brew install bat
brew install watch
