brew cask install amethyst
brew cask install iterm2
brew cask install virtualbox
brew cask install boostnote
brew cask install ngrok
brew cask install visual-studio-code
brew cask install font-firacode-nerd-font
brew cask install sqlworkbenchj
brew cask install clipy
brew cask install dbeaver-community
brew cask install apptivate
brew cask install loom
brew cask install postman
brew cask install workspaces
brew cask install google-chrome
brew cask install intellij-idea-ce
brew cask install docker
brew cask install spectacle
brew cask install google-cloud-sdk
brew cask install figma
brew cask install whatsapp
brew cask install skype
brew cask install slack
brew cask install alfred
brew cask install font-hack-nerd-font
